<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="4" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-29T20:23:58 IST" name="Suite" finished-at="2024-12-29T20:24:47 IST" duration-ms="49062">
    <groups>
    </groups>
    <test started-at="2024-12-29T20:23:58 IST" name="File Upload Register Test" finished-at="2024-12-29T20:24:47 IST" duration-ms="49062">
      <class name="DemoAutomation.Tests.FileUploadRegisterSubmit">
        <test-method signature="fileRegister(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:23:59 IST" name="fileRegister" data-provider="getFileUploadData" finished-at="2024-12-29T20:24:09 IST" duration-ms="10642" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[henryricherrymvc923356@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[A!@#$poiu9876]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[I:\Excel-Automation-main\Excel-Automation-main\TestData\dummy.pdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User successfully registere] but found [User successfully registered.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User successfully registere] but found [User successfully registered.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister(FileUploadRegisterSubmit.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fileRegister -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:09 IST" name="tearDown" finished-at="2024-12-29T20:24:10 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="fileRegister(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:10 IST" name="fileRegister" data-provider="getFileUploadData" finished-at="2024-12-29T20:24:19 IST" duration-ms="9936" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[jackreacheryedmvc456@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[A!@#$poiu9875]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[I:\Excel-Automation-main\Excel-Automation-main\TestData\dummy.pdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User successfully registere] but found [User successfully registered.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User successfully registere] but found [User successfully registered.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister(FileUploadRegisterSubmit.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fileRegister -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:20 IST" name="tearDown" finished-at="2024-12-29T20:24:20 IST" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="fileRegister(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:20 IST" name="fileRegister" data-provider="getFileUploadData" finished-at="2024-12-29T20:24:31 IST" duration-ms="10980" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[maxwellgainedmvc4657@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[A!@#$poiu9874]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[I:\Excel-Automation-main\Excel-Automation-main\TestData\dummy.pdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User successfully registere] but found [User successfully registered.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User successfully registere] but found [User successfully registered.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister(FileUploadRegisterSubmit.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fileRegister -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:31 IST" name="tearDown" finished-at="2024-12-29T20:24:31 IST" duration-ms="131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="fileRegister(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:31 IST" name="fileRegister" data-provider="getFileUploadData" finished-at="2024-12-29T20:24:47 IST" duration-ms="15886" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrishshakespearcmvc57871@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[A!@#$poiu9873]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[I:\Excel-Automation-main\Excel-Automation-main\TestData\dummy.pdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User successfully registere] but found [User successfully registered.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User successfully registere] but found [User successfully registered.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister(FileUploadRegisterSubmit.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fileRegister -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:47 IST" name="tearDown" finished-at="2024-12-29T20:24:47 IST" duration-ms="142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="errorHandling(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]" started-at="2024-12-29T20:24:47 IST" name="errorHandling" finished-at="2024-12-29T20:24:47 IST" depends-on-methods="DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DemoAutomation.Tests.FileUploadRegisterSubmit.errorHandling() on instance DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907 depends on not successfully finished methods 
[DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister() on instance DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DemoAutomation.Tests.FileUploadRegisterSubmit.errorHandling() on instance DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907 depends on not successfully finished methods 
[DemoAutomation.Tests.FileUploadRegisterSubmit.fileRegister() on instance DemoAutomation.Tests.FileUploadRegisterSubmit@7098b907]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorHandling -->
      </class> <!-- DemoAutomation.Tests.FileUploadRegisterSubmit -->
    </test> <!-- File Upload Register Test -->
  </suite> <!-- Suite -->
</testng-results>
